DaliCMS/Models/StudentRespAdultRel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DaliCMS.Models
{
    public class StudentRespAdultRel
    {
        [Key]
        public int Id { get; set; }
        public int StudentId { get; set; }
        public virtual Student StudentModel { get; set; }
        public int ResponsibleAdultId { get; set; }
        public virtual ResponsibleAdult ResponsibleAdultModel { get; set; }
    }
}

DaliCMS/Controllers/StudentRespAdultRelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DaliCMS.Models;
using X.PagedList;

namespace DaliCMS.Controllers
{
    public class StudentRespAdultRelsController : Controller
    {
        private DaliCMSContext db = new DaliCMSContext();

        // GET: StudentRespAdultRels
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var studentsRespAdultsRel = db.StudentsRespAdultsRel.Include(s => s.ResponsibleAdultModel).Include(s => s.StudentModel);

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            if (!string.IsNullOrEmpty(searchString))
            {
                studentsRespAdultsRel = studentsRespAdultsRel.Where(s => s.ResponsibleAdultModel.Name.Contains(searchString) || s.StudentModel.Name.Contains(searchString));
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.RsAdSortParm = String.IsNullOrEmpty(sortOrder) ? "ResponsibleAdultName_desc" : "";
            ViewBag.StdtSortParm = sortOrder == "StudentName" ? "StudentName_desc" : "StudentName";

            switch (sortOrder)
            {
                case "ResponsibleAdultName_desc":
                    studentsRespAdultsRel = studentsRespAdultsRel.OrderByDescending(s => s.ResponsibleAdultModel.Name);
                    break;
                case "StudentName":
                    studentsRespAdultsRel = studentsRespAdultsRel.OrderBy(s => s.StudentModel.Name);
                    break;
                case "StudentName_desc":
                    studentsRespAdultsRel = studentsRespAdultsRel.OrderByDescending(s => s.StudentModel.Name);
                    break;
                default:
                    studentsRespAdultsRel = studentsRespAdultsRel.OrderBy(s => s.ResponsibleAdultModel.Name);
                    break;
            }

            int DefaultPageSize = 10;
            int currentPageIndex = (page ?? 1);
            return View(studentsRespAdultsRel.ToPagedList(currentPageIndex, DefaultPageSize));
        }

        // GET: StudentRespAdultRels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRespAdultRel studentRespAdultRel = db.StudentsRespAdultsRel.Find(id);
            if (studentRespAdultRel == null)
            {
                return HttpNotFound();
            }
            return View(studentRespAdultRel);
        }

        // GET: StudentRespAdultRels/Create
        public ActionResult Create()
        {
            ViewBag.ResponsibleAdultId = new SelectList(db.ResponsibleAdults, "Id", "Name");
            ViewBag.StudentId = new SelectList(db.Students, "Id", "Name");
            return View();
        }

        // POST: StudentRespAdultRels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StudentId,ResponsibleAdultId")] StudentRespAdultRel studentRespAdultRel)
        {
            if (ModelState.IsValid)
            {
                db.StudentsRespAdultsRel.Add(studentRespAdultRel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ResponsibleAdultId = new SelectList(db.ResponsibleAdults, "Id", "Name", studentRespAdultRel.ResponsibleAdultId);
            ViewBag.StudentId = new SelectList(db.Students, "Id", "Name", studentRespAdultRel.StudentId);
            return View(studentRespAdultRel);
        }

        // GET: StudentRespAdultRels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRespAdultRel studentRespAdultRel = db.StudentsRespAdultsRel.Find(id);
            if (studentRespAdultRel == null)
            {
                return HttpNotFound();
            }
            ViewBag.ResponsibleAdultId = new SelectList(db.ResponsibleAdults, "Id", "Name", studentRespAdultRel.ResponsibleAdultId);
            ViewBag.StudentId = new SelectList(db.Students, "Id", "Name", studentRespAdultRel.StudentId);
            return View(studentRespAdultRel);
        }

        // POST: StudentRespAdultRels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StudentId,ResponsibleAdultId")] StudentRespAdultRel studentRespAdultRel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentRespAdultRel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ResponsibleAdultId = new SelectList(db.ResponsibleAdults, "Id", "Name", studentRespAdultRel.ResponsibleAdultId);
            ViewBag.StudentId = new SelectList(db.Students, "Id", "Name", studentRespAdultRel.StudentId);
            return View(studentRespAdultRel);
        }

        // GET: StudentRespAdultRels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentRespAdultRel studentRespAdultRel = db.StudentsRespAdultsRel.Find(id);
            if (studentRespAdultRel == null)
            {
                return HttpNotFound();
            }
            return View(studentRespAdultRel);
        }

        // POST: StudentRespAdultRels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudentRespAdultRel studentRespAdultRel = db.StudentsRespAdultsRel.Find(id);
            db.StudentsRespAdultsRel.Remove(studentRespAdultRel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DaliCMS/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DaliCMS.Models;
using X.PagedList;

namespace DaliCMS.Controllers
{
    public class StudentsController : Controller
    {
        private DaliCMSContext db = new DaliCMSContext();

        // GET: Students
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var students = db.Students.Include(s => s.LevelModel).Include(s => s.SchoolModel);
            
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            if (!string.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.Name.Contains(searchString));
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.DebtSortParm = sortOrder == "Debt" ? "Debt_desc" : "Debt";
            ViewBag.LevlSortParm = sortOrder == "Level" ? "Level_desc" : "Level";

            switch (sortOrder)
            {
                case "Name_desc":
                    students = students.OrderByDescending(s => s.Name);
                    break;
                case "Debt":
                    students = students.OrderBy(s => s.Debt);
                    break;
                case "Debt_desc":
                    students = students.OrderByDescending(s => s.Debt);
                    break;
                case "Level":
                    students = students.OrderBy(s => s.LevelModel.Name);
                    break;
                case "Level_desc":
                    students = students.OrderByDescending(s => s.LevelModel.Name);
                    break;
                default:
                    students = students.OrderBy(s => s.Name);
                    break;
            }

            foreach (Student student in students)
            {
                StudentRespAdultRel relations = student.StudentRespAdultRels.FirstOrDefault();
                int SignedUpChildrenPerRespAdult = 0;
                if (relations != null)
                {
                    SignedUpChildrenPerRespAdult = relations.ResponsibleAdultModel.StudentRespAdultRels.Count();
                }
                student.Siblings = SignedUpChildrenPerRespAdult >= 2;
            }

            int DefaultPageSize = 10;
            int currentPageIndex = (page ?? 1);
            return View(students.ToPagedList(currentPageIndex, DefaultPageSize));
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            ViewBag.LevelId = new SelectList(db.Levels, "Id", "Name");
            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,DNI,Address,City,Phone,Dateofbirth,Debt,LevelId,SchoolId")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                //CHECK ALL FIELDS
                return RedirectToAction("Index");
            }

            ViewBag.LevelId = new SelectList(db.Levels, "Id", "Name", student.LevelId);
            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name", student.SchoolId);
            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            ViewBag.LevelId = new SelectList(db.Levels, "Id", "Name", student.LevelId);
            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name", student.SchoolId);
            student.Debt = Convert.ToInt32(student.Debt);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,DNI,Address,City,Phone,Dateofbirth,Debt,LevelId,SchoolId")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LevelId = new SelectList(db.Levels, "Id", "Name", student.LevelId);
            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name", student.SchoolId);
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DaliCMS/Views/StudentRespAdultRels/Create.cshtml
@model DaliCMS.Models.StudentRespAdultRel

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Agregar relación</b></h1_special>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Nombre del alumno", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nombre del adulto responsable", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ResponsibleAdultId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ResponsibleAdultId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar relación" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista de relaciones", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DaliCMS/Views/StudentRespAdultRels/Delete.cshtml
@model DaliCMS.Models.StudentRespAdultRel

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Eliminar relación</b></h1_special>
<h3>Está seguro de querer eliminar esta relación?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre del alumno
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StudentModel.Name)
        </dd>
        <dt>
            Nombre del adulto responsable
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ResponsibleAdultModel.Name)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default btn-sm btn-danger" /> 
            @Html.ActionLink("Volver a la lista de relaciones", "Index", null, new { @class = "btn btn-primary btn-sm" })
        </div>
    }
</div>

DaliCMS/Views/StudentRespAdultRels/Edit.cshtml
@model DaliCMS.Models.StudentRespAdultRel

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Editar relación</b></h1_special>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Nombre del alumno", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nombre del adulto responsable", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ResponsibleAdultId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ResponsibleAdultId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar cambios" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista de relaciones", "Index", null, new { @class = "btn btn-primary btn-sm" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DaliCMS/Views/StudentRespAdultRels/Index.cshtml
@model X.PagedList.IPagedList<DaliCMS.Models.StudentRespAdultRel>
@using X.PagedList.Mvc;

@{
    ViewBag.Title = "Índice";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Alumnos/Adultos responsables</b></h1_special>
<br />
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Agregar nueva relación", "Create", null, new { @class = "btn btn-main-dali" })
        </th>
        <th>
            <div class="input-group col-sm-7 col-lg-offset-11 pull-right">
                @using (Html.BeginForm("Index", "StudentRespAdultRels", FormMethod.Get))
                {
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control input", @placeholder = "Nombre del adulto o del alumno..." })
                    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                }
            </div>
        </th>
    </tr>
</table>
<br />
<table class="table">
    <tr bgcolor="#E5E5E5">
        <th>
            @Html.ActionLink("Nombre del Adulto responsable", "Index", new { sortOrder = ViewBag.RsAdSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Nombre del alumno", "Index", new { sortOrder = ViewBag.StdtSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Acciones
        </th>
    </tr>

    @foreach (var item in Model) {
        <tr bgcolor="#E5E5E5">
            <td>
                @Html.ActionLink(item.ResponsibleAdultModel.Name, "Details", "ResponsibleAdults", new { Id = item.ResponsibleAdultModel.Id }, null)
            </td>
            <td>
                @Html.ActionLink(item.StudentModel.Name, "Details", "Students", new { Id = item.StudentModel.Id }, null)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id=item.Id }, new { @class = "btn btn-success btn-sm" }) 
                @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }

</table>


@if (Model.PageCount > 1)
{
    <div class="pager">@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort }))</div>
}