DaliCMS/Controllers/LevelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DaliCMS.Models;
using X.PagedList;

namespace DaliCMS.Controllers
{
    public class LevelsController : Controller
    {
        private DaliCMSContext db = new DaliCMSContext();

        // GET: Levels
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var levels = (IQueryable<Level>)db.Levels;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            if (!string.IsNullOrEmpty(searchString))
            {
                levels = levels.Where(s => s.Name.Contains(searchString));
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.PrceSortParm = sortOrder == "BasePrice" ? "BasePrice_desc" : "BasePrice";

            switch (sortOrder)
            {
                case "Name_desc":
                    levels = levels.OrderByDescending(s => s.Name);
                    break;
                case "BasePrice":
                    levels = levels.OrderBy(s => s.BasePrice);
                    break;
                case "BasePrice_desc":
                    levels = levels.OrderByDescending(s => s.BasePrice);
                    break;
                default:
                    levels = levels.OrderBy(s => s.Name);
                    break;
            }

            int DefaultPageSize = 10;
            int currentPageIndex = (page ?? 1);
            return View(levels.ToPagedList(currentPageIndex, DefaultPageSize));
        }

        // GET: Levels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Level level = db.Levels.Find(id);
            if (level == null)
            {
                return HttpNotFound();
            }
            return View(level);
        }

        // GET: Levels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Levels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,BasePrice")] Level level)
        {
            if (ModelState.IsValid)
            {
                db.Levels.Add(level);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(level);
        }

        // GET: Levels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Level level = db.Levels.Find(id);
            if (level == null)
            {
                return HttpNotFound();
            }
            return View(level);
        }

        // POST: Levels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,BasePrice")] Level level)
        {
            if (ModelState.IsValid)
            {
                db.Entry(level).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(level);
        }

        // GET: Levels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Level level = db.Levels.Find(id);
            if (level == null)
            {
                return HttpNotFound();
            }
            return View(level);
        }

        // POST: Levels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Level level = db.Levels.Find(id);
            db.Levels.Remove(level);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DaliCMS/Controllers/SchoolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DaliCMS.Models;
using X.PagedList;

namespace DaliCMS.Controllers
{
    public class SchoolsController : Controller
    {
        private DaliCMSContext db = new DaliCMSContext();

        // GET: Schools
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var schools = (IQueryable<School>)db.Schools;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            if (!string.IsNullOrEmpty(searchString))
            {
                schools = schools.Where(s => s.Name.Contains(searchString) && !s.Name.Contains("No es estudiante"));
            }
            else
            {
                schools = schools.Where(s => !s.Name.Contains("No es estudiante"));
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.AddrSortParm = sortOrder == "Address" ? "Address_desc" : "Address";
            ViewBag.CitySortParm = sortOrder == "City" ? "City_desc" : "City";
            ViewBag.PhneSortParm = sortOrder == "Phone" ? "Phone_desc" : "Phone";

            switch (sortOrder)
            {
                case "Name_desc":
                    schools = schools.OrderByDescending(s => s.Name);
                    break;
                case "Address":
                    schools = schools.OrderBy(s => s.Address);
                    break;
                case "Address_desc":
                    schools = schools.OrderByDescending(s => s.Address);
                    break;
                case "City":
                    schools = schools.OrderBy(s => s.City);
                    break;
                case "City_desc":
                    schools = schools.OrderByDescending(s => s.City);
                    break;
                case "Phone":
                    schools = schools.OrderBy(s => s.Phone);
                    break;
                case "Phone_desc":
                    schools = schools.OrderByDescending(s => s.Phone);
                    break;
                default:
                    schools = schools.OrderBy(s => s.Name);
                    break;
            }

            int DefaultPageSize = 10;
            int currentPageIndex = (page ?? 1);
            return View(schools.ToPagedList(currentPageIndex, DefaultPageSize));
        }

        // GET: Schools/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        // GET: Schools/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Schools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Address,City,Phone")] School school)
        {
            if (ModelState.IsValid)
            {
                db.Schools.Add(school);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(school);
        }

        // GET: Schools/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        // POST: Schools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Address,City,Phone")] School school)
        {
            if (ModelState.IsValid)
            {
                db.Entry(school).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(school);
        }

        // GET: Schools/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        // POST: Schools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            School school = db.Schools.Find(id);
            db.Schools.Remove(school);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DaliCMS/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DaliCMS.Models;
using X.PagedList;

namespace DaliCMS.Controllers
{
    public class StudentsController : Controller
    {
        private DaliCMSContext db = new DaliCMSContext();

        // GET: Students
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var students = db.Students.Include(s => s.LevelModel).Include(s => s.SchoolModel);
            
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            if (!string.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.Name.Contains(searchString));
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.DebtSortParm = sortOrder == "Debt" ? "Debt_desc" : "Debt";
            ViewBag.LevlSortParm = sortOrder == "Level" ? "Level_desc" : "Level";

            switch (sortOrder)
            {
                case "Name_desc":
                    students = students.OrderByDescending(s => s.Name);
                    break;
                case "Debt":
                    students = students.OrderBy(s => s.Debt);
                    break;
                case "Debt_desc":
                    students = students.OrderByDescending(s => s.Debt);
                    break;
                case "Level":
                    students = students.OrderBy(s => s.LevelModel.Name);
                    break;
                case "Level_desc":
                    students = students.OrderByDescending(s => s.LevelModel.Name);
                    break;
                default:
                    students = students.OrderBy(s => s.Name);
                    break;
            }

            foreach (Student student in students)
            {
                StudentRespAdultRel relations = student.StudentRespAdultRels.FirstOrDefault();
                int SignedUpChildrenPerRespAdult = 0;
                if (relations != null)
                {
                    SignedUpChildrenPerRespAdult = relations.ResponsibleAdultModel.StudentRespAdultRels.Count();
                }
                student.Siblings = SignedUpChildrenPerRespAdult >= 2;
            }

            int DefaultPageSize = 10;
            int currentPageIndex = (page ?? 1);
            return View(students.ToPagedList(currentPageIndex, DefaultPageSize));
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            ViewBag.LevelId = new SelectList(db.Levels, "Id", "Name");
            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,DNI,Address,City,Phone,Dateofbirth,Debt,LevelId,SchoolId")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                //CHECK ALL FIELDS
                return RedirectToAction("Index");
            }

            ViewBag.LevelId = new SelectList(db.Levels, "Id", "Name", student.LevelId);
            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name", student.SchoolId);
            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            ViewBag.LevelId = new SelectList(db.Levels, "Id", "Name", student.LevelId);
            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name", student.SchoolId);
            student.Debt = Convert.ToInt32(student.Debt);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,DNI,Address,City,Phone,Dateofbirth,Debt,LevelId,SchoolId")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LevelId = new SelectList(db.Levels, "Id", "Name", student.LevelId);
            ViewBag.SchoolId = new SelectList(db.Schools, "Id", "Name", student.SchoolId);
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DaliCMS/Views/Students/Create.cshtml
@model DaliCMS.Models.Student

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Agregar alumno</b></h1_special>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("DNI", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DNI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DNI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dirección", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ciudad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Teléfono", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Fecha de nacimiento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dateofbirth, new { htmlAttributes = new { @class = "form-control datecontrol" } })
                @Html.ValidationMessageFor(model => model.Dateofbirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Deuda al día", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Debt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Debt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nivel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LevelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LevelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Escuela", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SchoolId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SchoolId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar alumno" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista de alumnos", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DaliCMS/Views/Students/Delete.cshtml
@model DaliCMS.Models.Student

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Eliminar alumno</b></h1_special>
<h3>Está seguro de querer eliminar esta entrada?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            DNI
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DNI)
        </dd>

        <dt>
            Dirección
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            Ciudad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            Teléfono
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            Fecha de nacimiento
        </dt>

        <dd>
            @string.Format("{0:dd/MM/yyyy}", Model.Dateofbirth)
        </dd>

        <dt>
            Deuda al día
        </dt>

        <dd>
            $@Html.DisplayFor(model => model.Debt)
        </dd>

        <dt>
            Nivel
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LevelModel.Name)
        </dd>

        <dt>
            Escuela
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SchoolModel.Name)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default btn-sm btn-danger" /> 
            @Html.ActionLink("Volver a la lista de alumnos", "Index", null, new { @class = "btn btn-primary btn-sm" })
        </div>
    }
</div>

DaliCMS/Views/Students/Details.cshtml
@model DaliCMS.Models.Student

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Detalles del alumno</b></h1_special>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            DNI
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DNI)
        </dd>

        <dt>
            Dirección
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            Ciudad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            Teléfono
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            Fecha de nacimiento
        </dt>

        <dd>
            @string.Format("{0:dd/MM/yyyy}", Model.Dateofbirth)
        </dd>

        <dt>
            Deuda al día
        </dt>

        <dd>
            $@Html.DisplayFor(model => model.Debt)
        </dd>

        <dt>
            Nivel
        </dt>

        <dd>
            @Html.ActionLink(Model.LevelModel.Name, "Details", "Levels", new { Id = Model.LevelModel.Id }, null)
        </dd>

        @if (Model.SchoolModel.Name != "No es estudiante")
        {
            <dt>
                Escuela
            </dt>

            <dd>
                @Html.ActionLink(Model.SchoolModel.Name, "Details", "Schools", new { Id = Model.SchoolModel.Id }, null)
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-success btn-sm" }) 
    @Html.ActionLink("Volver a la lista de alumnos", "Index", null, new { @class = "btn btn-primary btn-sm" })
</p>

DaliCMS/Views/Students/Index.cshtml
@model X.PagedList.IPagedList<DaliCMS.Models.Student>
@using X.PagedList.Mvc;

@{
    ViewBag.Title = "Índice";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Alumnos</b></h1_special>
<br />
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Agregar nuevo alumno", "Create", null, new { @class = "btn btn-main-dali" })
        </th>
        <th>
            <div class="input-group col-sm-7 col-lg-offset-11 pull-right">
                @using (Html.BeginForm("Index", "Students", FormMethod.Get))
                {
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control input", @placeholder = "Nombre del alumno..." })
                    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                }
            </div>
        </th>
    </tr>
</table>
<br />
<table class="table">
    <tr bgcolor="#E5E5E5">
        <th>
            @Html.ActionLink("Nombre", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Deuda a la fecha", "Index", new { sortOrder = ViewBag.DebtSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Nivel", "Index", new { sortOrder = ViewBag.LevlSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Hermanos/as
        </th>
        <th style="text-align:center">
            Acciones
        </th>
    </tr>

    @foreach (var item in Model) {
        <tr bgcolor="#E5E5E5">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td style="font-weight:bold">
                $@Html.DisplayFor(modelItem => item.Debt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LevelModel.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Siblings)
            </td>
            <td align="center">
                @Html.ActionLink("Editar", "Edit", new { id=item.Id }, new { @class = "btn btn-success btn-sm" }) 
                @Html.ActionLink("Detalles", "Details", new { id=item.Id }, new { @class = "btn btn-primary btn-sm" }) 
                @Html.ActionLink("Registrar pago", "Create", "Payments", new { StudentId = item.Id }, new { @class = "btn btn-main-dali btn-sm" })
                @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }
</table>

@if (Model.PageCount > 1)
{
    <div class="pager">@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))</div>
}