DaliCMS/Models/ResponsibleAdult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DaliCMS.Models
{
    public class ResponsibleAdult
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string JobName { get; set; }
        public virtual ICollection<StudentRespAdultRel> StudentRespAdultRels { get; set; }
    }
}

DaliCMS/Controllers/ResponsibleAdultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DaliCMS.Models;
using X.PagedList;

namespace DaliCMS.Controllers
{
    public class ResponsibleAdultsController : Controller
    {
        private DaliCMSContext db = new DaliCMSContext();

        // GET: ResponsibleAdults
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {

            var responsibleadults = (IQueryable<ResponsibleAdult>)db.ResponsibleAdults;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            if (!string.IsNullOrEmpty(searchString))
            {
                responsibleadults = responsibleadults.Where(s => s.Name.Contains(searchString));
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.AddrSortParm = sortOrder == "Address" ? "Address_desc" : "Address";
            ViewBag.PhneSortParm = sortOrder == "Phone" ? "Phone_desc" : "Phone";
            ViewBag.JobNSortParm = sortOrder == "Job" ? "Job_desc" : "Job";

            switch (sortOrder)
            {
                case "Name_desc":
                    responsibleadults = responsibleadults.OrderByDescending(s => s.Name);
                    break;
                case "Address":
                    responsibleadults = responsibleadults.OrderBy(s => s.Address);
                    break;
                case "Address_desc":
                    responsibleadults = responsibleadults.OrderByDescending(s => s.Address);
                    break;
                case "Phone":
                    responsibleadults = responsibleadults.OrderBy(s => s.Phone);
                    break;
                case "Phone_desc":
                    responsibleadults = responsibleadults.OrderByDescending(s => s.Phone);
                    break;
                case "Job":
                    responsibleadults = responsibleadults.OrderBy(s => s.JobName);
                    break;
                case "Job_desc":
                    responsibleadults = responsibleadults.OrderByDescending(s => s.JobName);
                    break;
                default:
                    responsibleadults = responsibleadults.OrderBy(s => s.Name);
                    break;
            }

            int DefaultPageSize = 10;
            int currentPageIndex = (page ?? 1);
            return View(responsibleadults.ToPagedList(currentPageIndex, DefaultPageSize));
        }

        // GET: ResponsibleAdults/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResponsibleAdult responsibleAdult = db.ResponsibleAdults.Find(id);
            if (responsibleAdult == null)
            {
                return HttpNotFound();
            }
            return View(responsibleAdult);
        }

        // GET: ResponsibleAdults/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ResponsibleAdults/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Address,Phone,JobName")] ResponsibleAdult responsibleAdult)
        {
            if (ModelState.IsValid)
            {
                db.ResponsibleAdults.Add(responsibleAdult);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(responsibleAdult);
        }

        // GET: ResponsibleAdults/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResponsibleAdult responsibleAdult = db.ResponsibleAdults.Find(id);
            if (responsibleAdult == null)
            {
                return HttpNotFound();
            }
            return View(responsibleAdult);
        }

        // POST: ResponsibleAdults/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Address,Phone,JobName")] ResponsibleAdult responsibleAdult)
        {
            if (ModelState.IsValid)
            {
                db.Entry(responsibleAdult).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(responsibleAdult);
        }

        // GET: ResponsibleAdults/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResponsibleAdult responsibleAdult = db.ResponsibleAdults.Find(id);
            if (responsibleAdult == null)
            {
                return HttpNotFound();
            }
            return View(responsibleAdult);
        }

        // POST: ResponsibleAdults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ResponsibleAdult responsibleAdult = db.ResponsibleAdults.Find(id);
            db.ResponsibleAdults.Remove(responsibleAdult);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DaliCMS/Views/ResponsibleAdults/Create.cshtml
@model DaliCMS.Models.ResponsibleAdult

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Agregar adulto responsable</b></h1_special>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dirección", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Teléfono", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Empleo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar adulto responsable" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista de adultos responsables", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DaliCMS/Views/ResponsibleAdults/Delete.cshtml
@model DaliCMS.Models.ResponsibleAdult

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Eliminar adulto responsable</b></h1_special>
<h3>Está seguro de querer eliminar esta entrada?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Dirección
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            Teléfono
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            Empleo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default btn-sm btn-danger" /> 
            @Html.ActionLink("Volver a la lista de adultos responsables", "Index", null, new { @class = "btn btn-primary btn-sm" })
        </div>
    }
</div>

DaliCMS/Views/ResponsibleAdults/Details.cshtml
@model DaliCMS.Models.ResponsibleAdult

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Detalles del adulto responsable</b></h1_special>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Dirección
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            Teléfono
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            Empleo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-success btn-sm" })
    @Html.ActionLink("Volver a la lista de adultos responsables", "Index", null, new { @class = "btn btn-primary btn-sm" })
</p>

DaliCMS/Views/ResponsibleAdults/Edit.cshtml
@model DaliCMS.Models.ResponsibleAdult

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Editar adulto responsable</b></h1_special>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dirección", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Teléfono", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Empleo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar cambios" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista de adultos responsables", "Index", null, new { @class = "btn btn-primary btn-sm" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DaliCMS/Views/ResponsibleAdults/Index.cshtml
@model X.PagedList.IPagedList<DaliCMS.Models.ResponsibleAdult>
@using X.PagedList.Mvc;

@{
    ViewBag.Title = "Índice";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Adultos responsables</b></h1_special>
<br />
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Agregar adulto responsable", "Create", null, new { @class = "btn btn-main-dali" })
        </th>
        <th>
            <div class="input-group col-sm-7 col-lg-offset-11 pull-right">
                @using (Html.BeginForm("Index", "ResponsibleAdults", FormMethod.Get))
                {
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control input", @placeholder = "Nombre del adulto responsable..." })
                    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                }
            </div>
        </th>
    </tr>
</table>
<br />
<table class="table">
    <tr bgcolor="#E5E5E5">
        <th>
            @Html.ActionLink("Nombre", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Dirección", "Index", new { sortOrder = ViewBag.AddrSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Teléfono", "Index", new { sortOrder = ViewBag.PhneSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Empleo", "Index", new { sortOrder = ViewBag.JobNSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Acciones
        </th>
    </tr>

@foreach (var item in Model) {
    <tr bgcolor="#E5E5E5">
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobName)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }, new { @class = "btn btn-success btn-sm" }) 
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }, new { @class = "btn btn-danger btn-sm" })
        </td>
    </tr>
}

</table>


@if (Model.PageCount > 1)
{
    <div class="pager">@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort }))</div>
}