DaliCMS/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DaliCMS.Models
{
    public class Payment
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "El monto del pago es obligatorio")]
        public decimal Amount { get; set; }
        public decimal CancellationAmount { get; set; }
        public bool HasDiscount { get; set; }
        public bool HasPenalty { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "La fecha del pago es obligatorio")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime PaymentDate { get; set; }
        [Required(ErrorMessage = "El mes-año asociado a este pago es obligatorio")]
        [DisplayFormat(DataFormatString = "{0:MM/yyyy}")]
        public DateTime MonthYearPaid { get; set; }
        public int StudentId { get; set; }
        public virtual Student StudentModel { get; set; }
    }
}

DaliCMS/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DaliCMS.Models;
using X.PagedList;

namespace DaliCMS.Controllers
{
    public class PaymentsController : Controller
    {
        private DaliCMSContext db = new DaliCMSContext();

        // GET: Payments
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var payments = db.Payments.Include(p => p.StudentModel);

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            if (!string.IsNullOrEmpty(searchString))
            {
                payments = payments.Where(s => s.StudentModel.Name.Contains(searchString));
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "Name";
            ViewBag.AmntSortParm = sortOrder == "Amount" ? "Amount_desc" : "Amount";
            ViewBag.MnthSortParm = sortOrder == "MonthYearPaid" ? "" : "MonthYearPaid";
            ViewBag.DsctSortParm = sortOrder == "HasDiscount" ? "HasDiscount_desc" : "HasDiscount";
            ViewBag.PnltSortParm = sortOrder == "HasPenalty" ? "HasPenalty_desc" : "HasPenalty";
            ViewBag.DateSortParm = sortOrder == "PaymentDate" ? "PaymentDate_desc" : "PaymentDate";

            switch (sortOrder)
            {
                case "Name":
                    payments = payments.OrderBy(s => s.StudentModel.Name);
                    break;
                case "Name_desc":
                    payments = payments.OrderByDescending(s => s.StudentModel.Name);
                    break;
                case "Amount":
                    payments = payments.OrderBy(s => s.Amount);
                    break;
                case "Amount_desc":
                    payments = payments.OrderByDescending(s => s.Amount);
                    break;
                case "MonthYearPaid":
                    payments = payments.OrderBy(s => s.MonthYearPaid);
                    break;
                case "HasDiscount":
                    payments = payments.OrderBy(s => s.HasDiscount);
                    break;
                case "HasDiscount_desc":
                    payments = payments.OrderByDescending(s => s.HasDiscount);
                    break;
                case "HasPenalty":
                    payments = payments.OrderBy(s => s.HasPenalty);
                    break;
                case "HasPenalty_desc":
                    payments = payments.OrderByDescending(s => s.HasPenalty);
                    break;
                case "PaymentDate":
                    payments = payments.OrderBy(s => s.PaymentDate);
                    break;
                case "PaymentDate_desc":
                    payments = payments.OrderByDescending(s => s.PaymentDate);
                    break;
                default:
                    payments = payments.OrderByDescending(s => s.MonthYearPaid);
                    break;
            }

            int DefaultPageSize = 10;
            int currentPageIndex = (page ?? 1);
            return View(payments.ToPagedList(currentPageIndex, DefaultPageSize));
        }

        // GET: Payments/Create
        public ActionResult Create(int StudentId = 0)
        {
            if (StudentId == 0)
            {
                ViewBag.StudentId = new SelectList(db.Students, "Id", "Name");
            }
            else
            {
                ViewBag.StudentId = new SelectList(db.Students, "ID", "Name", db.Students.Select(x => x.Id == StudentId).FirstOrDefault());
            }
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Amount,CancellationAmount,HasDiscount,HasPenalty,PaymentDate,MonthYearPaid,StudentId")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                db.Payments.Add(payment);
                Student student = db.Students.Find(payment.StudentId);
                if (student == null)
                {
                    return HttpNotFound();
                }
                decimal adjustment = 0;
                payment.HasDiscount = false;
                payment.HasPenalty = false;
                if (payment.PaymentDate.Day <= 10 && (payment.PaymentDate.Month == payment.MonthYearPaid.Month && payment.PaymentDate.Year == payment.MonthYearPaid.Year))
                {
                    adjustment = adjustment + 5;
                    payment.HasDiscount = true;
                }
                else if (payment.PaymentDate.Month < payment.MonthYearPaid.Month || payment.PaymentDate.Year < payment.MonthYearPaid.Year)
                {
                    adjustment = adjustment + 5;
                    payment.HasDiscount = true;
                }
                else if (payment.PaymentDate.Month > payment.MonthYearPaid.Month || payment.PaymentDate.Year > payment.MonthYearPaid.Year)
                {
                    adjustment = adjustment - 10;
                    payment.HasPenalty = true;
                }
                List<StudentRespAdultRel> ResponsibleAdultsRel = student.StudentRespAdultRels.Where(Rel => Rel.StudentId == student.Id).ToList();
                foreach (StudentRespAdultRel RespAdultRel in ResponsibleAdultsRel)
                {
                    ResponsibleAdult RA = RespAdultRel.ResponsibleAdultModel;
                    if (RA.StudentRespAdultRels.Where(Rel => Rel.ResponsibleAdultId == RA.Id).ToList().Count() > 1)
                    {
                        adjustment = adjustment + 20;
                        payment.HasDiscount = true;
                        break;
                    }
                }
                payment.CancellationAmount = payment.Amount / (100 - adjustment) * 100;
                student.Debt = student.Debt - payment.CancellationAmount;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StudentId = new SelectList(db.Students, "Id", "Name", payment.StudentId);
            return View(payment);
        }

        // GET: Payments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.Find(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Payment payment = db.Payments.Find(id);
            Student student = db.Students.Find(payment.StudentId);
            if (student == null)
            {
                return HttpNotFound();
            }
            student.Debt = student.Debt + payment.CancellationAmount;
            db.Payments.Remove(payment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public JsonResult GetStudentDebt(string StudentId)
        {
            int Student = Convert.ToInt32(StudentId);
            Student SelectedStudent = db.Students.FirstOrDefault(s => s.Id == Student);
            if (SelectedStudent != null)
            {
                return Json(new { success = true, studentDebt = Convert.ToDecimal(SelectedStudent.Debt) }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false });
        }

        //This implementation of the "GetStudentSiblings" is working and even though it's faster now, it's still somewhat slow - need to make it faster.
        [HttpPost]
        public JsonResult GetStudentSiblings(string StudentId)
        {
            int Student = Convert.ToInt32(StudentId);
            int? SiblingsCount = db.Students.FirstOrDefault(s => s.Id == Student)?.StudentRespAdultRels.FirstOrDefault()?.ResponsibleAdultModel.StudentRespAdultRels.Count();
            if (SiblingsCount != null && SiblingsCount >= 2)
            {
                return Json(new { success = true, studentSiblings = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, studentSiblings = false }, JsonRequestBehavior.AllowGet);
        }
    }
}

DaliCMS/Views/Payments/Create.cshtml
@model DaliCMS.Models.Payment

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<div id="myOverlay"></div>
<h1_special class="text-center"><b>Agregar pago</b></h1_special>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Alumno", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @id = "studentSelected", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Deuda a la fecha", htmlAttributes: new { @class = "text-right col-md-2" })
            <div class="col-md-10">
                @Html.Label(" ", htmlAttributes: new { @id = "studentDebt", @class = "badge" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Hermanos/as", htmlAttributes: new { @class = "text-right col-md-2" })
            <div class="col-md-10">
                @Html.CheckBox("Hermanos/as", htmlAttributes: new { @id = "siblings", disabled = "disabled" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Monto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Fecha de pago", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control datecontrol" } })
                @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mes/año pagado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MonthYearPaid, new { htmlAttributes = new { @class = "form-control", @id = "myDatepicker" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="submitPayment" value="Agregar pago" class="btn btn-success"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista de pagos", "Index", null, new { @class = "btn btn-primary" })
    <div id="loadingGIF" style="display: none;"><img src="/Content/images/ajax-loader.gif" /></div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $('#myDatepicker').datepicker({
                format: "mm/yyyy",
                startView: "year",
                minViewMode: "months",
                language: "es",
            })
        });
        $(function () {
            $('#submitPayment').click(function () {
                document.getElementById("myDatepicker").value = $('#myDatepicker').val().toString().replace(/\//i, "\/01\/");
                return true;
            });
        });
        $(document).ready(function () {
            $('#myOverlay').css({ "position": "fixed", "left": "0", "height": "100%", "width": "100%", "background": "black", "opacity": ".15", "z-index": "2" }).fadeIn(500);
            $('#loadingGIF').css({ "position": "fixed", "top": "33%", "left": "50%", "z-index": "3" }).fadeIn(500);
            var StudentSelected = $('#studentSelected').val();
            if (StudentSelected !== "") {
                $.ajax({
                    url: '@Url.Action("GetStudentDebt", "Payments")',
                    type: 'POST',
                    data: {
                        StudentId: StudentSelected,
                    },
                    success: function (result1) {
                        $('#studentDebt').text("$" + result1.studentDebt);
                    }
                });
                $.ajax({
                    url: '@Url.Action("GetStudentSiblings", "Payments")',
                    type: 'POST',
                    data: {
                        StudentId: StudentSelected,
                    },
                    success: function (result2) {
                        $('#siblings').prop('checked', result2.studentSiblings);
                        $('#myOverlay').fadeOut(500);
                        $('#loadingGIF').fadeOut(500);
                    }
                });
            }
        });
        $(function () {
            $("#studentSelected").change(function () {
                $('#myOverlay').css({ "position": "fixed", "left": "0", "height": "100%", "width": "100%", "background": "black", "opacity": ".15", "z-index": "2" }).fadeIn();
                $('#loadingGIF').css({ "position": "fixed", "top": "33%", "left": "50%", "z-index": "3" }).fadeIn();
                var StudentSelected = $(this).val();
                if (StudentSelected !== "") {
                    $.ajax({
                        url: '@Url.Action("GetStudentDebt", "Payments")',
                        type: 'POST',
                        data: {
                            StudentId: StudentSelected,
                        },
                        success: function (result1) {
                            $('#studentDebt').text("$" + result1.studentDebt);
                        }
                    });
                    $.ajax({
                        url: '@Url.Action("GetStudentSiblings", "Payments")',
                        type: 'POST',
                        data: {
                            StudentId: StudentSelected,
                        },
                        success: function (result2) {
                            $('#siblings').prop('checked', result2.studentSiblings);
                            $('#myOverlay').fadeOut();
                            $('#loadingGIF').fadeOut();
                        }
                    });
                }
            });
        });
    </script>
}

DaliCMS/Views/Payments/Delete.cshtml
@model DaliCMS.Models.Payment

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Eliminar pago</b></h1_special>
<h3>Está seguro de querer eliminar esta entrada?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre del alumno
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StudentModel.Name)
        </dd>
        <dt>
            Monto
        </dt>
        <dd>
            $@Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            Mes/año pagado
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MonthYearPaid)
        </dd>
        <dt>
            Tiene descuento?
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HasDiscount)
        </dd>
        <dt>
            Tiene recargo?
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HasPenalty)
        </dd>
        <dt>
            Fecha de pago
        </dt>
        <dd>
            @Model.PaymentDate.ToString("dd/MM/yyyy")
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default btn-sm btn-danger" /> 
            @Html.ActionLink("Volver a la lista de pagos", "Index", null, new { @class = "btn btn-primary btn-sm" })
        </div>
    }
</div>

DaliCMS/Views/Payments/Index.cshtml
@model X.PagedList.IPagedList<DaliCMS.Models.Payment>
@using X.PagedList.Mvc;

@{
    ViewBag.Title = "Índice";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Account/Login/");
    }
}

<h1_special class="text-center"><b>Pagos</b></h1_special>
<br />
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Agregar pago", "Create", null, new { @class = "btn btn-main-dali" })
        </th>
        <th>
            <div class="input-group col-sm-7 col-lg-offset-11 pull-right">
                @using (Html.BeginForm("Index", "Payments", FormMethod.Get))
                {
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control input", @placeholder = "Nombre del alumno..." })
                    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                }
            </div>
        </th>
    </tr>
</table>
<br />
<table class="table">
    <tr bgcolor="#E5E5E5">
        <th>
            @Html.ActionLink("Nombre del alumno", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Monto", "Index", new { sortOrder = ViewBag.AmntSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Mes/año pagado", "Index", new { sortOrder = ViewBag.MnthSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Tiene descuento?", "Index", new { sortOrder = ViewBag.DsctSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Tiene recargo?", "Index", new { sortOrder = ViewBag.PnltSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Fecha de pago", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Acciones
        </th>
    </tr>

    @foreach (var item in Model) {
        <tr bgcolor="#E5E5E5">
            <td>
                @Html.DisplayFor(modelItem => item.StudentModel.Name)
            </td>
            <td style="font-weight:bold">
                $@Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.MonthYearPaid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HasDiscount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HasPenalty)
            </td>
            <td>
                @item.PaymentDate.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }

</table>


@if (Model.PageCount > 1)
{
    <div class="pager">@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort }))</div>
}